INDIGO_WELCOME_MESSAGE: "Dive in and learn about cryptocurrency and markets!"
INDIGO_PRIMARY_COLOR: "#2fa4e7" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "https://blockscholars.org/about"
  - title: "Contact"
    url: "https://blockscholars.org/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "https://blockscholars.org/tos"
    - title: "Indigo theme for Open edX"
      url: "https://github.com/overhangio/indigo"
